### ISSUE TITLE
Working on 3.0.3 #2

### ISSUE THREAD

**Issue by bpreiss13** [lucian979/CarletonBD#2]
I've extracted the markup starting with the query key to the batman.txt file but I'm not sure if that's all I'm supposed to do? Am I supposed to run it through some sort of postprocessing to make the textfile look nice? Right now it's a mostly unreadable jumble of markup which is fine, but not sure if I'm supposed to do more

**Comment by bpreiss13** [comment]
[batman (1).txt](https://github.com/lucian979/CarletonBD/files/5888853/batman.1.txt)
This is my current file

**Comment by lucian979** [comment]
Hi Ben,

you're almost there!  the markup starts with:
{{About|the superhero}}\n{{redirect|Bruce Wayne}}\n{{pp-semi-indef}}\n{{pp-move-indef}}\n{{short description|Fictional superhero}}\n{{Use mdy dates|date=July 2020}}\n{{Infobox comics character\n| character_name = Batman<br>{{small|\'\'\'Bruce Wayne\'\'\'}}\n| image...

so you need to make your way further in.  to get the markup use this:
markup = list(data['query']['pages'].values())[0]['revisions'][0]['*']

and save that to the file.

**Comment by bpreiss13** [comment]
Ah okay I got it now, thank you!
