### ISSUE TITLE
Requesting Game of Thrones Data

### ISSUE THREAD

**Issue by bpreiss13** [lucian979/CarletonBD#3]
I understand this was done in exercise 1, but I messed up my jupyter notebook a while ago and lost all of my work from E1 and E2. Reworking through it now for assignment 1, but everytime I do the  line"data =rq.get("https://www.reddit.com/r/gameofthrones/.json").json()" I'm getting the too many requests error. I understand there's not an easy way around it because reddit is limiting the number requests to their server but I'm not sure why I keep getting it after leaving my code for 10-15 minutes and running it again. And I'm worried even with fixing it everytime I add new code to the cell and want to test it that I would run into it again. Would there be a way to hardsave the .json data to the kernel?

**Comment by lucian979** [comment]
it's because your request is anonymous and there's too many of them apparently.  you need a user-agent, see below, it could be any string doesn't have to be '000'.

response = rq.get('https://www.reddit.com/r/gameofthrones/.json', headers={'User-agent': '000'})
