### ISSUE TITLE
Decision Tree

### ISSUE THREAD

**Issue by bpreiss13** [lucian979/CarletonBD#4]
Been working on 5.1.3 for a very long time today and read chapter 17 a couple of times but still cannot figure out how to implement a decision tree or find the maximum entropy path. My code I currently have always wants to split the data on the team with the least members. Really not sure where to go from here, feel like my code is super bloated and wonky. Think it went pretty wrong early on as I wasn't sure how to translate the functions seen in the book which utilized a dictionary with tuples as their main input to our binary arrays. Attached my attempt below but think it's probably pretty far-off base, not sure. 
<img width="993" alt="Screen Shot 2021-02-14 at 5 18 32 PM" src="https://user-images.githubusercontent.com/55596319/107882280-b0a4f200-6ee8-11eb-9dfe-b16a18578a64.png">

**Comment by bpreiss13** [comment]
realizing now that my function isn't finding split entropy but rather finding the entropy of whether or not a given character is on each team. Not sure how to figure out the split entropy en masse though. Tried making a dictionary similar to the one in chapter 17 earlier but I couldn't get around the error of incorrect type (ndarray being an unhashable object)

**Comment by lucian979** [comment]
It's a bit unclear how you're approaching this problem.  So I've sketched out below how you should break the problem down.  This should clarify things.

First, you will need the function implemented in 5.1.2 that computes the weighted average entropy for a particular split (it takes as input args: the data matrix, the target array, and the name of the team to split on) and returns the weighted average entropy.  Make sure you have it.

Then, to implement a decision tree, you need to follow this structure:

current_x = x

current_y = y

while more than 5 data points in current_x:

​		(new_x, new_y) = split_on_minimum_entropy_team(current_x, current_y)

​		current_x = new_x

​		current_y = new_y



so now you need to code split_on_minimum_entropy_team.  something along the lines:

* go through all the teams and compute the split entropy for each using the function you wrote in 5.1.2.  you have to be careful here: if a team has is no characters on it in the current data set, it means you've already split on it before, so set that split entropy to 1 so it doesn't mess up the following step:
* then find the minimum among those split entropies
* then split the data based on that team (the one that gives the minimum entropy). to make the code less clunky, write a function which does this part: split_on_team(data, target, team)



code this function: split_on_team(data, target, team).  it split data into data0 and data1 based on the charcaters belonging to "team", and the corresponding target0 and target 1. compute the entropies within each subset and return either data0 and target 0 or data1 and target1, depending on which has the highest entropy.

Let me know if this helps.  Also, happy to meet and discuss.
